package com.heymaster.heymaster.model.home

data class ObjectXX(
    val accountNonExpired: Boolean,
    val accountNonLocked: Boolean,
    val active: Boolean,
    val alreadyIsMaster: Boolean,
    val approximateEndTime: Any,
    val attachments: List<Any>,
    val authorities: List<AuthorityX>,
    val birthDate: String,
    val busy: Boolean,
    val createAt: String,
    val createdBy: Any,
    val credentialsNonExpired: Boolean,
    val device: DeviceX,
    val enabled: Boolean,
    val experienceYear: Int,
    val fullName: String,
    val gender: Boolean,
    val generatePassword: String,
    val id: Int,
    val location: Location,
    val password: String,
    val peopleReitedCount: Int,
    val phoneNumber: String,
    val professionList: List<ProfessionX>,
    val profilePhoto: ProfilePhoto,
    val roles: RolesX,
    val salary: Any,
    val totalMark: Int,
    val updateAt: String,
    val updatedBy: Int,
    val username: String
)