package com.heymaster.heymaster.model.booking

data class From(
    val accountNonExpired: Boolean,
    val accountNonLocked: Boolean,
    val active: Boolean,
    val alreadyIsMaster: Boolean,
    val approximateEndTime: Any,
    val attachments: List<Any>,
    val authorities: List<Authority>,
    val birthDate: Any,
    val busy: Boolean,
    val createAt: String,
    val createdBy: Any,
    val credentialsNonExpired: Boolean,
    val device: Device,
    val enabled: Boolean,
    val experienceYear: Int,
    val fullName: String?,
    val gender: Boolean,
    val generatePassword: String,
    val id: Int,
    val location: Any,
    val password: String,
    val peopleReitedCount: Int,
    val phoneNumber: String?,
    val professionList: List<Profession>,
    val profilePhoto: Any,
    val roles: Roles,
    val salary: Any,
    val totalMark: Int,
    val updateAt: String,
    val updatedBy: Any,
    val username: String
)